### ISSUE TITLE
Crash on trigger

### ISSUE THREAD

**Issue by rbau28** [Elmegaard/QuickStash#5]
[Player.log](https://github.com/Elmegaard/QuickStash/files/8838567/Player.log)

Hi.

Upon pressing the hotkey to trigger the mod, it caused the game to crash.

**Comment by Elmegaard** [comment]
Can you attach your BePinEx log as well? It has the info I need. It is located in "VRising\BepInEx\LogOutput.log"

**Comment by rbau28** [comment]
[LogOutput.log](https://github.com/Elmegaard/QuickStash/files/8839320/LogOutput.log)

here you go. It happened just now for the 2nd time. Its triggered when I use the hotkey. Not sure if its a compatibility issue with other mods.

Also unlike before where the items are transferred before the crash, this time it isnt.

**Comment by Elmegaard** [comment]
Hmm it looks weird, there are no issues in the log I can see. But I have some ideas for what it could be anyway, I'll try and see if I can fix it anyway.

**Comment by Elmegaard** [comment]
Try the latest version, it should be fixed now.

**Comment by rbau28** [comment]
[Error  :   BepInEx] Error loading [quick_stash 1.2.3]: System.TypeLoadException: Could not resolve type with token 01000037 from typeref (expected class 'Wetstone.API.VNetworkRegistry' in assembly 'Wetstone, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null')
  at vrising_stash.Plugin.Load () [0x00027] in <bd321214cda8495a81083c73cd35adff>:0
  at BepInEx.IL2CPP.IL2CPPChainloader.LoadPlugin (BepInEx.PluginInfo pluginInfo, System.Reflection.Assembly pluginAssembly) [0x00011] in <20831d408969472ba3d48658d4a1512f>:0
  at BepInEx.Bootstrap.BaseChainloader`1[TPlugin].Execute () [0x00284] in <91aaa8349151457a98c04caf9728bc52>:0

This is the new error Im getting upon booting V Rising

**Comment by rbau28** [comment]
It's also generating an error when attempting to trigger the quickstash when using 1.2.3. It also does nothing. but the settings still shows the option to set the hotkey.

**Comment by Elmegaard** [comment]
Do you have the latest QuickStash and Wetstone on both the server and client?

**Comment by rbau28** [comment]
Yes i think so.

Server/Client has 1.2.3 Quickstash
Wetstone is v1.1

**Comment by aianlinb** [comment]
I have the same issue with both latest version

**Comment by Elmegaard** [comment]
I just tried a fresh install of both Wetstone and Quickstash 1.2.3 and it works for me. It looks like a Wetstone issue from the logs though. Can you try and reinstall both Wetstone and Quickstash in both the server and client?

**Comment by aianlinb** [comment]
I just restart the game and the issue is gone...
But some time it still happen when first trigger after launch the game

**Comment by Elmegaard** [comment]
Since I haven't heard any more of this I assume it's solved.
